environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

install:
  - "%PYTHON%\\python.exe --version"

build_script:
  - "%PYTHON%\\python.exe -m pip install requests"
  - "%PYTHON%\\python.exe -m pip install awkward numba scipy"
  - "%PYTHON%\\python.exe -m pip install pytest pytest-runner"
  - "%PYTHON%\\python.exe setup.py pytest"
