name: Build, Deploy, and Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #
        java-version: [1.8]
        python-version: [3.6] #
        awkward-version: ['awkward>=0.8.4']
    name: build coffea (${{ matrix.os }}) - python ${{ matrix.python-version }}, JDK${{ matrix.java-version }}

    steps:
    - uses: actions/checkout@master
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Install dependencies
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install -q --upgrade pip setuptools setuptools_scm wheel six pytest codecov
        python -m pip install -q ${{ matrix.awkward-version }}
        python -m pip install -q https://github.com/Parsl/parsl/zipball/master
        python -m pip install -q -e .[parsl,dask,spark]
        python -m pip list
        java -version
    - name: Test with pytest
      env:
        ARROW_PRE_0_15_IPC_FORMAT: 1
      run: |
        coverage run --source=coffea/ setup.py pytest
    - name: Upload codecov
      if: success()
      run: |
        codecov
    - name: Install pandoc
      if: success()
      uses: r-lib/actions/setup-pandoc@v1
    - name: Install graphviz
      if: success()
      uses: kamiazya/setup-graphviz@v1
    - name: Build documentation
      if: success()
      run: |
        source docs/build_docs.sh
    - name: Deploy documentation
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.0.1
      with:
        target_branch: gh-pages
        build_dir: docs/build/html
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_OAUTH }}
    - name: Create Release
      if: success()
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_OAUTH }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Build package for PyPI
      if: success()
      run: |
        python setup.py sdist bdist_wheel --universal
    - name: Publish package to PyPI
      if: success()
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
